# Sample docker-compose.yml

version: "3.0"

services:
  relay:
    image: natechoe/tor-relay
    container_name: tor-relay
    hostname: tor-relay
    ports:
      - "200:200"
    environment:
      - RELAY_NICKNAME=natestorrelay
      - RELAY_CONTACT=nate@natechoe.dev
      - RELAY_PORT=200
      - RELAY_EXIT=0
      - RELAY_BANDWIDTH=25MBytes
    restart:
      always
